name: apres-ski
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.5.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2022.10.11
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.1.3
  - comm=0.1.2
  - contourpy=1.0.5
  - cryptography=38.0.1
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - flit-core=3.6.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - icu=68.1
  - idna=3.4
  - importlib-metadata=4.11.3
  - ipykernel=6.19.2
  - ipython=8.7.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.16.0
  - jupyter_client=7.4.8
  - jupyter_core=5.1.1
  - jupyter_server=1.23.4
  - jupyterlab=3.5.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.16.5
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=14.0.6
  - libdeflate=1.8
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libopenblas=0.3.21
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.4.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - llvm-openmp=14.0.6
  - lxml=4.9.1
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - munkres=1.1.4
  - nbclassic=0.4.8
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openssl=1.1.1s
  - packaging=22.0
  - pandas=1.5.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pip=22.3.1
  - platformdirs=2.5.2
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.15
  - python-dateutil=2.8.2
  - python-dotenv=0.21.0
  - python-fastjsonschema=2.16.2
  - pytz=2022.7
  - pyzmq=23.2.0
  - readline=8.2
  - redis-py=4.4.0
  - requests=2.28.1
  - seaborn=0.12.1
  - send2trash=1.8.0
  - setuptools=65.5.0
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - spotipy=2.20.0
  - sqlite=3.40.0
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.7.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.13
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1
  - xz=5.2.8
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - blis==0.7.9
    - catalogue==2.0.8
    - confection==0.0.4
    - cymem==2.0.7
    - en-core-web-sm==3.4.1
    - exceptiongroup==1.1.0
    - iniconfig==2.0.0
    - langcodes==3.3.0
    - langdetect==1.0.9
    - lyricsgenius==3.0.1
    - murmurhash==1.0.9
    - pathy==0.10.1
    - plotly==5.12.0
    - pluggy==1.0.0
    - preshed==3.0.8
    - pydantic==1.10.4
    - pytest==7.2.1
    - scipy==1.10.0
    - smart-open==6.3.0
    - spacy==3.4.4
    - spacy-language-detection==0.2.1
    - spacy-legacy==3.0.11
    - spacy-loggers==1.0.4
    - srsly==2.4.5
    - tenacity==8.1.0
    - thinc==8.1.7
    - tqdm==4.64.1
    - typer==0.7.0
    - wasabi==0.10.1
